using SereneCycle.Domain.Content;
using SereneCycle.Domain.Cycles;
using SereneCycle.Domain.Entities;

namespace SereneCycle.Infrastructure.Persistence;

/// <summary>
/// Foliküler faz kataloğu. Bu fazın izleği: toparlanan enerji ve yükselen
/// östrojen. Yiyeceklerde protein, lif ve fermente seçenekler; hareketlerde
/// tempoyu yeniden artırmaya uygun, çeşitli yoğunluklarda öneriler.
///
/// Süreler bilinçli olarak 5 dakikadan 45 dakikaya kadar dağıtıldı: süre
/// filtresi sert bir kısıttır, "10 dakikam var" diyen kullanıcıya listeyi
/// boş döndürmemenin tek yolu her aralıkta aday bulundurmaktır.
/// </summary>
internal static class FollicularSeedData
{
    private static readonly PhaseSeed Phase = new(CyclePhase.Follicular);

    public static readonly IReadOnlyList<ContentItem> All =
    [
        // --- Öncelik verilebilecek yiyecekler ---
        Phase.Food("Yumurta",
            "Kaliteli protein; yükselen enerjiyi desteklemeye uygun bir kahvaltı olabilir.",
            [TasteTag.Eggs],
            [ContraTag.Vegan, ContraTag.EggAllergy]),
        Phase.Food("Yumurtalı tam tahıllı tost",
            "Protein ve kompleks karbonhidratı birleştirir; sabah tokluğunu uzatabilir.",
            [TasteTag.Eggs, TasteTag.WholeGrains],
            [ContraTag.Vegan, ContraTag.EggAllergy, ContraTag.Gluten]),
        Phase.Food("Avokado",
            "Sağlıklı yağlar içerir; hormon üretimi için gereken yağ asitlerini sağlar.",
            [TasteTag.Fruit, TasteTag.Vegetables]),
        Phase.Food("Yeşil yapraklılar",
            "Folat ve lif açısından zengin; günlük sebze çeşitliliğini artırmanın kolay yolu.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Semizotu",
            "Omega-3 içeren nadir yeşilliklerden; yoğurtla da salata olarak da tüketilebilir.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Marul ve mevsim yeşillikleri",
            "Lif ve su oranı yüksek; öğünlerin yanına hacim katar.",
            [TasteTag.LeafyGreens]),
        Phase.Food("Brokoli",
            "Turpgiller ailesinden; östrojen metabolizmasını desteklediği düşünülen bileşikler içerir.",
            [TasteTag.Vegetables]),
        Phase.Food("Karnabahar",
            "Lifli ve doyurucu; fırında pişirmek tatlılığını öne çıkarır.",
            [TasteTag.Vegetables]),
        Phase.Food("Brüksel lahanası",
            "C vitamini ve lif içerir; turpgillerin bu fazda öne çıkan üyelerinden.",
            [TasteTag.Vegetables]),
        Phase.Food("Lahana turşusu",
            "Fermente bir sebze; bağırsak florasını desteklediği düşünülür.",
            [TasteTag.Fermented, TasteTag.Vegetables]),
        Phase.Food("Kimchi",
            "Fermente ve baharatlı; az miktarda bile öğüne canlılık katar.",
            [TasteTag.Fermented, TasteTag.Spicy, TasteTag.Vegetables]),
        Phase.Food("Kefir",
            "Probiyotik içerir; sindirim düzenine katkısı olabilir.",
            [TasteTag.Dairy, TasteTag.Fermented],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Süzme yoğurt",
            "Yoğurda göre daha yoğun protein; ara öğün olarak doyurucu.",
            [TasteTag.Dairy],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Beyaz peynir",
            "Kalsiyum ve protein kaynağı; kahvaltıyı dengelemek için pratik.",
            [TasteTag.Dairy],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Yeşil mercimek salatası",
            "Bitkisel protein ve lif; soğuk tüketilebildiği için hazırlığı kolay.",
            [TasteTag.Legumes, TasteTag.Vegetables]),
        Phase.Food("Nohutlu salata",
            "Tok tutar ve kan şekerini daha dengeli tutmaya yardımcı olabilir.",
            [TasteTag.Legumes, TasteTag.Vegetables]),
        Phase.Food("Bezelye",
            "Bitkisel protein içerir; dondurulmuşu da besin değerini büyük ölçüde korur.",
            [TasteTag.Legumes]),
        Phase.Food("Kinoa",
            "Glutensiz bir tam tahıl; tüm temel amino asitleri içerir.",
            [TasteTag.WholeGrains]),
        Phase.Food("Bulgur pilavı",
            "Lifi yüksek bir tahıl; beyaz pirince göre kan şekerini daha yavaş yükseltir.",
            [TasteTag.WholeGrains],
            [ContraTag.Gluten]),
        Phase.Food("Tam tahıllı makarna",
            "Antrenman öncesi enerji için uygun; sebzeyle birleştirmek dengeler.",
            [TasteTag.WholeGrains],
            [ContraTag.Gluten]),
        Phase.Food("Izgara tavuk salatası",
            "Protein ve sebzeyi tek tabakta toplar; ağırlık yapmadan doyurur.",
            [TasteTag.Poultry, TasteTag.Vegetables],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Tavuk göğsü",
            "Yağı düşük protein kaynağı; artan aktiviteye eşlik edebilir.",
            [TasteTag.Poultry],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Uskumru",
            "Omega-3 bakımından zengin; haftada bir iki kez balık hedeflemek iyi bir alışkanlık.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Levrek",
            "Hafif ve kolay sindirilen bir balık; fırında pişirmek pratik.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Karides",
            "Yağı düşük, proteini yüksek bir deniz ürünü; hızlı pişer.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan, ContraTag.Shellfish]),
        Phase.Food("Badem",
            "E vitamini ve magnezyum içerir; bir avuç ara öğün için yeterli.",
            [TasteTag.NutsAndSeeds],
            [ContraTag.TreeNuts]),
        Phase.Food("Keten tohumu",
            "Lif ve lignan içerir; öğütülmüş hâli daha iyi değerlendirilir.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Ay çekirdeği",
            "E vitamini kaynağı; salataya çıtırlık katar.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Çilek",
            "C vitamini ve antioksidan içerir; şeker isteğine hafif bir cevap olabilir.",
            [TasteTag.Fruit]),
        Phase.Food("Yeşil elma",
            "Lifi yüksek; kabuğuyla tüketmek daha faydalı olabilir.",
            [TasteTag.Fruit]),
        Phase.Food("Greyfurt",
            "C vitamini içerir ve suyu boldur; kahvaltıyı ferahlatır.",
            [TasteTag.Fruit]),
        Phase.Food("Hurma",
            "Doğal şeker ve lif içerir; antrenman öncesi hızlı enerji sağlayabilir.",
            [TasteTag.Sweet, TasteTag.Fruit]),
        Phase.Food("Meyveli yoğurt kâsesi",
            "Tatlı isteğini protein ve meyveyle karşılamanın bir yolu.",
            [TasteTag.Sweet, TasteTag.Dairy, TasteTag.Fruit],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Pul biberli sebze sote",
            "Baharat, sebzeyi daha çok tüketmeyi kolaylaştırabilir.",
            [TasteTag.Spicy, TasteTag.Vegetables]),
        Phase.Food("Zerdeçallı sebze yemeği",
            "Zerdeçalın iltihap üzerindeki etkisi araştırılıyor; lezzet olarak da hoş bir seçenek.",
            [TasteTag.Spicy, TasteTag.Vegetables]),
        Phase.Food("Tarhana çorbası",
            "Fermente bir geleneksel çorba; ılık ve hafif bir akşam öğünü olabilir.",
            [TasteTag.LightSoup, TasteTag.Fermented],
            [ContraTag.Gluten]),
        Phase.Food("Domates çorbası",
            "Likopen içerir; hafif bir başlangıç olarak iş görür.",
            [TasteTag.LightSoup, TasteTag.Vegetables]),

        // --- Sınırlı tutulabilecek yiyecekler ---
        Phase.LimitFood("İşlenmiş şeker",
            "Enerji dalgalanmalarına yol açabilir; dengeli tüketmek daha iyi.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Alkol",
            "Uyku kalitesini düşürebilir; toparlanan enerjiyi geri çekebilir."),
        Phase.LimitFood("Enerji içecekleri",
            "Yüksek kafein ve şeker, huzursuzluk ve çarpıntı hissi yapabilir."),
        Phase.LimitFood("Fast food",
            "Tuz ve doymuş yağ oranı yüksektir; sık tüketimi enerjiyi düşürebilir."),
        Phase.LimitFood("Beyaz ekmek",
            "Lifi düşüktür; kan şekerini hızlı yükseltip hızlı düşürebilir."),
        Phase.LimitFood("Aşırı kafein",
            "Uykuya geçişi zorlaştırabilir; öğleden sonrası için azaltmak iyi olabilir."),
        Phase.LimitFood("Paketli meyve suları",
            "Lifi alınmış, şekeri yoğunlaşmıştır; meyvenin kendisi daha iyi bir seçenek.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Hazır soslar",
            "Şeker ve tuzu beklenmedik ölçüde yüksek olabilir; etiketi okumak yardımcı olur."),
        Phase.LimitFood("Cips ve tuzlu krakerler",
            "Tuz ve rafine yağ oranı yüksek; şişkinlik hissini artırabilir."),
        Phase.LimitFood("Şekerli kahve içecekleri",
            "Bir bardağı günlük şeker alımının önemli kısmını karşılayabilir.",
            [TasteTag.Sweet]),

        // --- İyi gelebilecek hareketler ---
        Phase.Exercise("Dinamik ısınma",
            "Kısa ve ekipmansız; asıl antrenmandan önce sakatlanma riskini azaltır.",
            5,
            [TasteTag.Stretching]),
        Phase.Exercise("Yerinde tempolu adımlama",
            "Nabzı yükseltmenin en pratik yolu; televizyon karşısında bile yapılabilir.",
            8,
            [TasteTag.Cardio]),
        Phase.Exercise("Sabah esnemesi",
            "Uykudan çıkan bedeni yavaşça açar; günü hareketle başlatır.",
            10,
            [TasteTag.Stretching]),
        Phase.Exercise("Sabah kısa yürüyüşü",
            "Gün ışığı ve hafif hareket; güne başlamanın en düşük eşikli yolu.",
            10,
            [TasteTag.Walking, TasteTag.Outdoor]),
        Phase.Exercise("İp atlama",
            "Kısa sürede yüksek kalori yakımı; darbe içerdiği için tempoyu kademeli artırmak iyi.",
            10,
            [TasteTag.Cardio, TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Merdiven çıkma",
            "Ekipman gerektirmez; kısa sürede nabzı belirgin yükseltir.",
            10,
            [TasteTag.Cardio],
            [ContraTag.Knee]),
        Phase.Exercise("Ayakta yoga dizisi",
            "Yere inmeyi gerektirmez; denge ve dikkat çalıştırır.",
            12,
            [TasteTag.Yoga]),
        Phase.Exercise("Kısa HIIT devresi",
            "Yüksek yoğunlukta kısa aralıklar; toparlanma kapasitesi bu fazda genelde daha iyidir.",
            15,
            [TasteTag.Hiit, TasteTag.Cardio],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Güneşe selam serisi",
            "Isınma ve akış bir arada; tekrar sayısını kendine göre ayarlayabilirsin.",
            15,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Duvar pilatesi",
            "Duvarı destek alarak yapılan kontrollü hareketler; mat gerekmez.",
            15,
            [TasteTag.Pilates]),
        Phase.Exercise("Serbest dans",
            "Çalma listesini aç ve bırak; hareket etmenin en az planlı hâli.",
            15,
            [TasteTag.Dance]),
        Phase.Exercise("Koşu-yürüyüş dönüşümlü tur",
            "Bir dakika koş, iki dakika yürü; koşuya dönmenin en yumuşak yolu.",
            15,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Tempolu yürüyüş",
            "Nefesin biraz açıldığı bir tempo; her yerde yapılabilir.",
            20,
            [TasteTag.Walking, TasteTag.Cardio]),
        Phase.Exercise("Vücut ağırlığı devresi",
            "Ekipmansız kuvvet; artan enerjiyi değerlendirmek için uygun.",
            20,
            [TasteTag.Strength],
            [ContraTag.Knee]),
        Phase.Exercise("Squat ve hamle çalışması",
            "Alt vücudu hedefler; formu korumak ağırlıktan önemli.",
            20,
            [TasteTag.Strength],
            [ContraTag.Knee]),
        Phase.Exercise("Tabata",
            "Yirmi saniye çalış, on saniye dinlen; kısa ama yorucu.",
            20,
            [TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Gölge boks",
            "Koordinasyon ve kardiyoyu birleştirir; ekipman gerektirmez ama omuzları çalıştırır.",
            20,
            [TasteTag.Hiit, TasteTag.Cardio],
            [ContraTag.Shoulder]),
        Phase.Exercise("Dans kardiyosu",
            "Kalori yakımını eğlenceyle birleştirir; takip etmesi kolay bir video yeterli.",
            30,
            [TasteTag.Dance, TasteTag.Cardio]),
        Phase.Exercise("Vinyasa yoga akışı",
            "Nefesle senkron geçişler; hem kuvvet hem esneklik ister.",
            30,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Mat pilatesi",
            "Merkez bölgeyi hedefleyen kontrollü hareketler.",
            30,
            [TasteTag.Pilates],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Dambıllı tam vücut antrenmanı",
            "Toparlanma kapasitesi bu fazda genelde daha iyidir; yükü kademeli artırmak iyi olur.",
            30,
            [TasteTag.Strength],
            [ContraTag.EquipmentDumbbell]),
        Phase.Exercise("Koşu bandında tempolu koşu",
            "Eğim ve hızı kontrol edebilmek temposunu korumayı kolaylaştırır.",
            30,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym, ContraTag.Knee]),
        Phase.Exercise("Yüzme",
            "Tüm vücudu çalıştırır ve eklemlere darbe binmez.",
            30,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Bisiklet turu",
            "Açık havada uzun ve keyifli bir kardiyo seçeneği.",
            40,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Salonda ağırlık antrenmanı",
            "Ekipman çeşitliliği yükü kademelendirmeyi kolaylaştırır.",
            45,
            [TasteTag.Strength],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Stüdyo pilatesi",
            "Eğitmen eşliğinde form düzeltmesi almanın en kolay yolu.",
            45,
            [TasteTag.Pilates],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Hafif eğimli doğa yürüyüşü",
            "Uzun ama tempoyu kendin belirlediğin bir seçenek; açık hava ruh hâline iyi gelebilir.",
            45,
            [TasteTag.Walking, TasteTag.Outdoor],
            [ContraTag.Knee]),

        Phase.Exercise("Yerinde jumping jack",
            "Kısa sürede nabzı yükseltir; darbe içerdiği için zemine dikkat.",
            8,
            [TasteTag.Cardio, TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Kalça köprüsü serisi",
            "Kalça ve arka bacak kaslarını hedefler; sırt üstü yapılır.",
            10,
            [TasteTag.Strength],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Plank varyasyonları",
            "Merkez bölgeyi çalıştırır; süreyi kademeli artırmak yeterli.",
            12,
            [TasteTag.Strength],
            [ContraTag.Shoulder]),
        Phase.Exercise("Sandalyeyle üst vücut kuvveti",
            "Ekipman yerine sandalye kullanır; ittirme hareketlerine giriş için iyi.",
            15,
            [TasteTag.Strength]),
        Phase.Exercise("Basamak çalışması",
            "Tek bir basamak yeterli; tempoyu kendin belirlersin.",
            15,
            [TasteTag.Cardio],
            [ContraTag.Knee]),
        Phase.Exercise("Latin dans akışı",
            "Adımları öğrenmek dikkat de gerektirir; enerji yüksekken keyifli.",
            20,
            [TasteTag.Dance]),
        Phase.Exercise("Omuz ve sırt açıcı yoga",
            "Masa başında geçen günleri dengelemeye yardımcı olabilir.",
            20,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Esneme ve mobilite seansı",
            "Eklem hareket açıklığına odaklanır; antrenman günleri arasına uyar.",
            25,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Bisiklet ergometresinde interval",
            "Direnç ve süreyi ayarlamak kolay; darbe içermez ama yoğun olabilir.",
            25,
            [TasteTag.Cardio, TasteTag.Hiit],
            [ContraTag.EquipmentGym, ContraTag.Knee]),
        Phase.Exercise("Tepe yürüyüşü",
            "Eğim, yürüyüşü kuvvet çalışmasına yaklaştırır.",
            30,
            [TasteTag.Walking, TasteTag.Outdoor],
            [ContraTag.Knee]),

        // --- Şimdilik ertelenebilecek hareketler ---
        Phase.SkipExercise("Uzun süreli hareketsizlik",
            "Enerjinin yükseldiği bu dönemde hareket etmek daha iyi hissettirebilir."),
        Phase.SkipExercise("Isınmadan ağır sete geçmek",
            "Hazırlanmamış kasta zorlanma riski artar; beş dakikalık ısınma yeterli.",
            [TasteTag.Strength]),
        Phase.SkipExercise("Üst üste yoğun antrenman günleri",
            "Toparlanma da programın parçası; iki yoğun gün arasına hafif bir gün koymak iyi olur.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Aşırı uzun kardiyo seansları",
            "Saatlerce süren tempo, kas kazanımını ve enerjini geri çekebilir.",
            [TasteTag.Cardio]),
        Phase.SkipExercise("Ağrıya rağmen devam etmek",
            "Yorgunluk ile ağrı farklıdır; ağrı bir durma sinyali olarak okunabilir."),
        Phase.SkipExercise("Yalnızca kardiyo yapmak",
            "Kuvvet çalışmasını tamamen atlamak uzun vadede dengeyi bozabilir.",
            [TasteTag.Cardio]),
        Phase.SkipExercise("Uykusuz günde yoğun antrenman",
            "Uyku borcu varken yoğunluk artırmak toparlanmayı zorlaştırır.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Bir günde iki yoğun ders",
            "Motivasyon yüksekken program aşmak, sonraki günlerin enerjisini borçlandırabilir.",
            [TasteTag.Cardio, TasteTag.Dance])
    ];
}
