using SereneCycle.Domain.Content;
using SereneCycle.Domain.Cycles;
using SereneCycle.Domain.Entities;

namespace SereneCycle.Infrastructure.Persistence;

/// <summary>
/// Luteal faz kataloğu. Bu fazın izleği: kan şekeri dalgalanması, tatlı
/// isteği, su tutulumu ve yavaşlayan toparlanma. Yiyeceklerde kompleks
/// karbonhidrat, magnezyum ve lif; hareketlerde orta yoğunluk ağırlıkta.
/// </summary>
internal static class LutealSeedData
{
    private static readonly PhaseSeed Phase = new(CyclePhase.Luteal);

    public static readonly IReadOnlyList<ContentItem> All =
    [
        // --- Öncelik verilebilecek yiyecekler ---
        Phase.Food("Tatlı patates",
            "Kompleks karbonhidrat; kan şekerini daha dengeli tutmaya yardımcı olabilir.",
            [TasteTag.Vegetables]),
        Phase.Food("Kabak",
            "Lifli ve hafif; fırında pişince doğal tatlılığı öne çıkar.",
            [TasteTag.Vegetables]),
        Phase.Food("Brokoli",
            "Lif ve C vitamini içerir; şişkinlik hissi olan günlerde buharda pişirmek daha rahat olabilir.",
            [TasteTag.Vegetables]),
        Phase.Food("Ispanak",
            "Magnezyum ve folat kaynağı; kas gerginliğine iyi gelebilir.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Karalahana",
            "Kalsiyum ve lif içerir; haşlayıp yemek sindirimi kolaylaştırır.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Semizotu salatası",
            "Hafif bir yeşillik; öğünlere hacim katarken ağırlık yapmaz.",
            [TasteTag.LeafyGreens]),
        Phase.Food("Mercimek",
            "Lif ve bitkisel protein; tokluk hissini destekler.",
            [TasteTag.Legumes]),
        Phase.Food("Nohutlu yemek",
            "Yavaş sindirilen karbonhidrat ve protein; tatlı isteğini azaltmaya yardımcı olabilir.",
            [TasteTag.Legumes]),
        Phase.Food("Barbunya",
            "Lif ve magnezyum içerir; kan şekerini dengede tutmaya yardımcı olabilir.",
            [TasteTag.Legumes]),
        Phase.Food("Yulaf lapası",
            "B6 ve magnezyum içerir; sıcak ve doyurucu bir kahvaltı seçeneği.",
            [TasteTag.WholeGrains],
            [ContraTag.Gluten]),
        Phase.Food("Esmer pirinç",
            "Lifi yüksek bir tahıl; öğünü daha dengeli hâle getirebilir.",
            [TasteTag.WholeGrains]),
        Phase.Food("Tam tahıllı ekmek",
            "Kan şekerini beyaz ekmeğe göre daha yavaş yükseltir.",
            [TasteTag.WholeGrains],
            [ContraTag.Gluten]),
        Phase.Food("Somon",
            "Omega-3 içerir; ruh hâli dalgalanmaları üzerindeki etkisi araştırılıyor.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Hamsi",
            "Omega-3 bakımından zengin ve ekonomik; fırında pişirmek pratik.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Hindi eti",
            "Triptofan içerir; akşam öğünü olarak tercih edilebilir.",
            [TasteTag.Poultry],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Tavuk çorbası",
            "Ilık ve hafif; iştahın düzensiz olduğu günlerde iyi gelebilir.",
            [TasteTag.Poultry, TasteTag.LightSoup],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Az yağlı dana eti",
            "Demir ve B12 içerir; porsiyonu küçük tutmak yeterli olabilir.",
            [TasteTag.RedMeat],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Yumurta",
            "Protein ve B vitaminleri; kahvaltıya protein eklemek tatlı isteğini azaltabilir.",
            [TasteTag.Eggs],
            [ContraTag.Vegan, ContraTag.EggAllergy]),
        Phase.Food("Yoğurt",
            "Kalsiyum ve probiyotik içerir; bazı çalışmalarda kalsiyumun PMS şikâyetlerini azalttığı bildirilmiştir.",
            [TasteTag.Dairy, TasteTag.Fermented],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Kefir",
            "Fermente bir içecek; şişkinlik hissi olan bazı kişilere iyi gelebilir.",
            [TasteTag.Dairy, TasteTag.Fermented],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Süzme peynir",
            "Yoğun protein; ara öğünde tatlı isteğini bastırmaya yardımcı olabilir.",
            [TasteTag.Dairy],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Tarçınlı süt",
            "Ilık ve tatlı; akşam rutinine yerleştirmesi kolay bir seçenek.",
            [TasteTag.Dairy, TasteTag.Spicy],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Badem",
            "Magnezyum ve E vitamini içerir; bir avuç ara öğün için yeterli.",
            [TasteTag.NutsAndSeeds],
            [ContraTag.TreeNuts]),
        Phase.Food("Ceviz",
            "Omega-3 ve magnezyum kaynağı; tatlı isteğine yağ ve lif ekleyerek cevap verir.",
            [TasteTag.NutsAndSeeds],
            [ContraTag.TreeNuts]),
        Phase.Food("Kabak çekirdeği",
            "Magnezyum bakımından zengin; kas gerginliğine katkısı olabilir.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Muz",
            "B6 ve potasyum içerir; şişkinlik ve kramp hissinde destekleyici olabilir.",
            [TasteTag.Fruit]),
        Phase.Food("Yaban mersini",
            "Antioksidan bakımından zengin; dondurulmuşu da kullanılabilir.",
            [TasteTag.Fruit]),
        Phase.Food("Kuru incir",
            "Lif ve kalsiyum içerir; tatlı isteğine daha dengeli bir cevap.",
            [TasteTag.Fruit, TasteTag.Sweet]),
        Phase.Food("Tarçınlı elma",
            "Lif ve baharatı birleştirir; fırında pişirmek tatlı yerine geçebilir.",
            [TasteTag.Fruit, TasteTag.Spicy]),
        Phase.Food("Bitter çikolata",
            "Magnezyum içerir; tatlı isteğine daha dengeli bir seçenek.",
            [TasteTag.Sweet]),
        Phase.Food("Hurmalı tahin",
            "Tatlıyı lif, yağ ve mineralle birlikte verir; bir porsiyon küçük tutulabilir.",
            [TasteTag.Sweet, TasteTag.NutsAndSeeds]),
        Phase.Food("Sebze çorbası",
            "Ilık ve hafif; akşam ağır yemek istemediğin günler için.",
            [TasteTag.LightSoup, TasteTag.Vegetables]),
        Phase.Food("Mercimek çorbası",
            "Protein ve lifi ılık bir öğünde birleştirir.",
            [TasteTag.LightSoup, TasteTag.Legumes]),
        Phase.Food("Zencefil ve tarçın çayı",
            "Şekersiz bir sıcak içecek; tatlı isteğini oyalamaya yardımcı olabilir.",
            [TasteTag.Spicy]),

        // --- Sınırlı tutulabilecek yiyecekler ---
        Phase.LimitFood("Aşırı kafein",
            "Kaygı ve göğüs hassasiyetini artırabilir."),
        Phase.LimitFood("Çok tuzlu atıştırmalıklar",
            "Su tutulumunu ve şişkinliği artırabilir."),
        Phase.LimitFood("Alkol",
            "Uyku kalitesini bozabilir; ruh hâli dalgalanmalarını derinleştirebilir."),
        Phase.LimitFood("Rafine şeker",
            "Hızlı yükselen kan şekeri, ardından gelen düşüşle tatlı isteğini büyütür.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Gazlı içecekler",
            "Gaz ve şişkinlik hissini artırabilir.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Çok yağlı ağır yemekler",
            "Sindirimi yavaşlatır; şişkinlik ve ağırlık hissini artırabilir."),
        Phase.LimitFood("Paketli hazır tatlılar",
            "Şeker ve rafine yağı bir arada verir; ev yapımı bir alternatif daha dengeli olabilir.",
            [TasteTag.Sweet]),
        Phase.LimitFood("İşlenmiş şarküteri",
            "Sodyumu yüksektir; su tutulumunu artırabilir."),
        Phase.LimitFood("Akşam saatlerinde kafein",
            "Uykuya geçişi zorlaştırabilir; bu fazda uyku kalitesi zaten dalgalanabilir."),
        Phase.LimitFood("Öğün atlamak",
            "Kan şekerinin düşmesi tatlı isteğini ve sinirlilik hissini artırabilir."),

        // --- İyi gelebilecek hareketler ---
        Phase.Exercise("Nefes ve gevşeme",
            "Yavaş nefes, gerginlik ve kaygı hissini azaltmaya yardımcı olabilir.",
            5,
            [TasteTag.Yoga]),
        Phase.Exercise("Boyun ve omuz esnemesi",
            "Kısa ve ekipmansız; masa başında bile yapılabilir.",
            8,
            [TasteTag.Stretching]),
        Phase.Exercise("Ayakta mobilite",
            "Hareketsiz geçen bir günü telafi etmenin en kısa yolu.",
            10,
            [TasteTag.Stretching]),
        Phase.Exercise("Sabah kısa yürüyüşü",
            "Gün ışığı ve hafif hareket, ruh hâli dalgalanmalarına iyi gelebilir.",
            10,
            [TasteTag.Walking, TasteTag.Outdoor]),
        Phase.Exercise("Ayakta yoga dizisi",
            "Yere inmeyi gerektirmez; denge ve dikkat çalıştırır.",
            12,
            [TasteTag.Yoga]),
        Phase.Exercise("Kalça ve bel esnemesi",
            "Bu bölgedeki gerginlik hissi bu fazda artabilir; nazik tutmak yeterli.",
            12,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Düşük etkili kısa HIIT",
            "Zıplama içermeyen bir yoğun aralık seçkisi; yoğunluğu kendin ayarlayabilirsin.",
            12,
            [TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Sandalye pilatesi",
            "Yere inmeden kontrollü hareketler; enerjisi düşük günlere uygun.",
            15,
            [TasteTag.Pilates]),
        Phase.Exercise("Duvar pilatesi",
            "Duvarı destek alarak yapılır; mat gerekmez.",
            15,
            [TasteTag.Pilates]),
        Phase.Exercise("Oturarak üst vücut kuvveti",
            "Bacaklara yük binmez; şişkinlik hissi olan günlerde daha rahat gelebilir.",
            15,
            [TasteTag.Strength]),
        Phase.Exercise("Akşam yürüyüşü",
            "Yemek sonrası yavaş bir tur, sindirime ve uykuya iyi gelebilir.",
            15,
            [TasteTag.Walking, TasteTag.Outdoor]),
        Phase.Exercise("Hafif tempolu yürüyüş",
            "Endorfin salınımı ruh hâline iyi gelebilir; tempoyu konuşabildiğin seviyede tut.",
            20,
            [TasteTag.Walking, TasteTag.Cardio]),
        Phase.Exercise("Yavaş tempolu dans",
            "Zorlamadan hareket etmenin keyifli yolu; ekipman gerekmez.",
            20,
            [TasteTag.Dance]),
        Phase.Exercise("Tam vücut esneme",
            "Baştan aşağı kısa duruşlar; toparlanmanın yavaşladığı bu fazda iyi gelebilir.",
            20,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Eliptik bisiklet",
            "Düşük direnç, eklemlere darbe bindirmeden nabzı yükseltir.",
            25,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Orta tempolu kuvvet devresi",
            "Yükü bir miktar düşürmek bu fazda mantıklı; hacmi korumak yeterli.",
            25,
            [TasteTag.Strength],
            [ContraTag.Knee]),
        Phase.Exercise("Dambıllı üst vücut",
            "Alt vücuda yük bindirmeyen bir kuvvet seçeneği.",
            25,
            [TasteTag.Strength],
            [ContraTag.EquipmentDumbbell]),
        Phase.Exercise("Dans kardiyosu",
            "Orta tempoda ve eğlenceli; motivasyonun düşük olduğu günlerde başlaması kolay.",
            25,
            [TasteTag.Dance, TasteTag.Cardio]),
        Phase.Exercise("Mat pilatesi",
            "Orta yoğunluk, güç ve esneklik dengesi sunar.",
            30,
            [TasteTag.Pilates],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Hatha yoga",
            "Pozlarda daha uzun kalınan yavaş bir yoga türü.",
            30,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Rahat tempoda yüzme",
            "Su, şişkinlik ve ağırlık hissini azaltabilir.",
            30,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Yavaş bisiklet turu",
            "Açık havada tempoyu kendin belirlediğin bir seçenek.",
            30,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Bahçe ya da balkon işleri",
            "Planlı bir antrenman değil ama gerçek bir hareket; açık hava da cabası.",
            30,
            [TasteTag.Outdoor]),
        Phase.Exercise("Restoratif yoga",
            "Destekli pozlarda uzun kalmak; çaba değil gevşeme hedefler.",
            35,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Yin yoga",
            "Pozlarda dakikalarca kalınır; derin dokuları nazikçe açmayı hedefler.",
            40,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Doğada yürüyüş",
            "Uzun ama sakin; açık hava ruh hâline iyi gelebilir.",
            40,
            [TasteTag.Walking, TasteTag.Outdoor],
            [ContraTag.Knee]),

        Phase.Exercise("Sandalyede nefes ve omuz açma",
            "Enerjinin en düşük olduğu günlerde bile sürdürülebilir.",
            8,
            [TasteTag.Yoga]),
        Phase.Exercise("Yatarak bacak esnetme",
            "Arka bacak kaslarını açar; bel bölgesini rahatlatabilir.",
            10,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Duvar squatı",
            "Duvara yaslanarak yapılır; kuvvet çalışmasının en kontrollü hâli.",
            10,
            [TasteTag.Strength],
            [ContraTag.Knee]),
        Phase.Exercise("Açık havada esneme molası",
            "Balkon ya da bahçe yeterli; gün ışığı ruh hâline iyi gelebilir.",
            12,
            [TasteTag.Stretching, TasteTag.Outdoor]),
        Phase.Exercise("Akşam esneme rutini",
            "Günü kapatan kısa bir seri; uykuya geçişi kolaylaştırabilir.",
            15,
            [TasteTag.Stretching]),
        Phase.Exercise("Sabah yoga selamı",
            "Yavaş tempoda birkaç tur; güne hareketle başlamanın sakin yolu.",
            15,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Nefes odaklı pilates",
            "Hareketi nefesle eşleştirir; yoğunluk düşük, kontrol yüksek.",
            20,
            [TasteTag.Pilates],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Hafif dambıllı alt vücut",
            "Ağırlığı düşürüp tekrarı korumak bu fazda daha iyi hissettirebilir.",
            20,
            [TasteTag.Strength],
            [ContraTag.EquipmentDumbbell, ContraTag.Knee]),
        Phase.Exercise("Havuzda yürüyüş",
            "Su, şişkinlik ve ağırlık hissini azaltır; eklemlere darbe binmez.",
            25,
            [TasteTag.Walking, TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Yavaş yoga akışı",
            "Geçişler yumuşak; toparlanmanın yavaşladığı bu fazda iyi oturur.",
            25,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),

        // --- Şimdilik ertelenebilecek hareketler ---
        Phase.SkipExercise("Ağır kaldırma",
            "Toparlanma bu fazda yavaşlayabilir; zorlanma riski artar.",
            [TasteTag.Strength]),
        Phase.SkipExercise("Yoğun HIIT",
            "Yüksek yoğunluk bu dönemde birçok kişiye olduğundan daha ağır gelir.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Kişisel rekor denemesi",
            "Performansın dalgalandığı bir faz; rekor için daha uygun bir hafta var.",
            [TasteTag.Strength]),
        Phase.SkipExercise("Yarış temposunda uzun kardiyo",
            "Uzun ve yüksek tempolu seanslar yorgunluğu derinleştirebilir.",
            [TasteTag.Cardio]),
        Phase.SkipExercise("Sıcak ortamda yoğun antrenman",
            "Vücut sıcaklığı bu fazda hafifçe yükselir; sıcak ortam zorlanmayı artırabilir."),
        Phase.SkipExercise("Karın bölgesine aşırı yüklenme",
            "Şişkinlik varsa zorlu karın çalışması rahatsızlık verebilir.",
            [TasteTag.Strength]),
        Phase.SkipExercise("Toparlanma günü bırakmamak",
            "Bu fazda dinlenme günü, antrenman günü kadar işe yarar."),
        Phase.SkipExercise("Uykusuzken yoğun seans",
            "Uyku kalitesi bu fazda dalgalanabilir; yoğunluğu uykuya göre ayarlamak iyi olur.",
            [TasteTag.Hiit])
    ];
}
