using SereneCycle.Domain.Content;
using SereneCycle.Domain.Cycles;
using SereneCycle.Domain.Entities;

namespace SereneCycle.Infrastructure.Persistence;

/// <summary>
/// Menstrüel faz kataloğu. Bu fazın izleği: kanamayla giden demir, kramp ve
/// şişkinlik, düşen enerji. Bu yüzden yiyeceklerde demir ve magnezyum,
/// hareketlerde nazik ve kısa seçenekler ağırlıkta.
///
/// Liste bilinçli olarak gösterilecek öğe sayısından kat kat uzun: ekranda
/// üç öğe görünürken aday sayısı otuzun üzerinde. Çeşitliliğin ve öğrenmenin
/// tavanını sıralama algoritması değil katalog boyutu belirler.
/// </summary>
internal static class MenstrualSeedData
{
    private static readonly PhaseSeed Phase = new(CyclePhase.Menstrual);

    public static readonly IReadOnlyList<ContentItem> All =
    [
        // --- Öncelik verilebilecek yiyecekler ---
        Phase.Food("Ispanak",
            "Demir ve folat içerir; kanamayla kaybedilen demiri desteklemeye yardımcı olabilir.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Pazı",
            "Magnezyum ve demir kaynağı; kas gevşemesine katkısı olabilir.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Roka",
            "K vitamini ve demir içerir; salatanın yanına eklemesi kolay bir seçenek.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Maydanozlu salata",
            "C vitamini bakımından zengin; bitkisel demirin emilimini destekleyebilir.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Kırmızı mercimek çorbası",
            "Bitkisel demir ve ılık sıvıyı bir arada verir; ağır gelmeyen bir öğün olabilir.",
            [TasteTag.Legumes, TasteTag.LightSoup]),
        Phase.Food("Nohut",
            "Demir ve protein içerir; tokluk hissini daha uzun tutabilir.",
            [TasteTag.Legumes]),
        Phase.Food("Kuru fasulye",
            "Lif ve bitkisel demir kaynağı; C vitamini içeren bir salatayla emilimi artabilir.",
            [TasteTag.Legumes]),
        Phase.Food("Yulaf ezmesi",
            "Magnezyum ve B grubu vitamin içerir; sıcak tüketmek bazı kişilere iyi gelir.",
            [TasteTag.WholeGrains],
            [ContraTag.Gluten]),
        Phase.Food("Tam buğday ekmeği",
            "Beyaz ekmeğe göre daha yavaş sindirilir; kan şekerini daha dengeli tutabilir.",
            [TasteTag.WholeGrains],
            [ContraTag.Gluten]),
        Phase.Food("Karabuğday pilavı",
            "Glutensiz bir tam tahıl; magnezyum içeriği kramplarda destekleyici olabilir.",
            [TasteTag.WholeGrains]),
        Phase.Food("Az yağlı dana eti",
            "Hem demiri içerir; bu form vücutta bitkisel demire göre daha kolay kullanılır.",
            [TasteTag.RedMeat],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Hindi göğsü",
            "Yağı düşük bir protein kaynağı; ağır gelmeden doyurabilir.",
            [TasteTag.Poultry],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Tavuk suyuna sebze çorbası",
            "Sıcak ve sıvı ağırlıklı; iştahın düşük olduğu günlerde daha kolay tüketilebilir.",
            [TasteTag.Poultry, TasteTag.LightSoup],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Somon",
            "Omega-3 içerir; bazı kişilerde kramp şiddetini azalttığı bildirilmiştir.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Sardalya",
            "Omega-3 ve kalsiyum içerir; konservesi pratik bir seçenek olabilir.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Haşlanmış yumurta",
            "B12 ve protein kaynağı; hazırlaması kolay olduğu için yorgun günlere uygun.",
            [TasteTag.Eggs],
            [ContraTag.Vegan, ContraTag.EggAllergy]),
        Phase.Food("Ispanaklı omlet",
            "Demir ve proteini tek tabakta toplar; kahvaltıyı atlamamak için pratik.",
            [TasteTag.Eggs, TasteTag.LeafyGreens],
            [ContraTag.Vegan, ContraTag.EggAllergy]),
        Phase.Food("Yoğurt",
            "Kalsiyum ve probiyotik içerir; sindirimi rahatlatabilir.",
            [TasteTag.Dairy, TasteTag.Fermented],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Kefir",
            "Fermente bir içecek; şişkinlik hissi olan bazı kişilere iyi gelebilir.",
            [TasteTag.Dairy, TasteTag.Fermented],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Tarçınlı sıcak süt",
            "Ilık ve tatlı bir seçenek; akşam rutinine yerleştirmesi kolay.",
            [TasteTag.Dairy, TasteTag.Spicy],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Ceviz",
            "Magnezyum kaynağı; kas gevşemesine katkı sağlayabilir.",
            [TasteTag.NutsAndSeeds],
            [ContraTag.TreeNuts]),
        Phase.Food("Kabak çekirdeği",
            "Demir ve magnezyum içerir; bir tutamı atıştırmalık olarak yeterli olabilir.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Tahin",
            "Kalsiyum ve demir içerir; bir kaşığı ekmeğin yanında hızlı bir destek olabilir.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Kuru kayısı",
            "Demir ve lif içerir; tatlı isteğine daha dengeli bir cevap olabilir.",
            [TasteTag.Fruit, TasteTag.Sweet]),
        Phase.Food("Portakal",
            "C vitamini, bitkisel demirin emilimini destekleyebilir.",
            [TasteTag.Fruit]),
        Phase.Food("Kivi",
            "C vitamini bakımından zengin; demir içeren bir öğünün yanında iyi gider.",
            [TasteTag.Fruit]),
        Phase.Food("Muz",
            "Potasyum ve B6 içerir; kas krampı olan bazı kişilerde rahatlatıcı olabilir.",
            [TasteTag.Fruit]),
        Phase.Food("Zencefil çayı",
            "Bazı çalışmalarda kramp şikâyetini azalttığı bildirilmiştir; ılık içmek rahatlatabilir.",
            [TasteTag.Spicy]),
        Phase.Food("Bitter çikolata",
            "Magnezyum içerir; tatlı isteğine daha dengeli bir seçenek olabilir.",
            [TasteTag.Sweet]),
        Phase.Food("Pekmez",
            "Geleneksel bir demir kaynağı; bir tatlı kaşığı tahinle birlikte tüketilebilir.",
            [TasteTag.Sweet]),
        Phase.Food("Sebze çorbası",
            "Sıvı alımını destekler; ağır gelmeyen sıcak bir öğün olabilir.",
            [TasteTag.LightSoup, TasteTag.Vegetables]),
        Phase.Food("Pancar",
            "Folat ve nitrat içerir; dolaşımı desteklediği düşünülür.",
            [TasteTag.Vegetables]),
        Phase.Food("Brokoli",
            "C vitamini ve lif içerir; demirli öğünlerin yanında iyi bir eşlikçi.",
            [TasteTag.Vegetables]),

        // --- Sınırlı tutulabilecek yiyecekler ---
        Phase.LimitFood("Aşırı tuz",
            "Şişkinlik hissini artırabilir; sınırlı tüketmek rahatlatabilir."),
        Phase.LimitFood("Kafein",
            "Bazı kişilerde kramp ve huzursuzluğu artırabilir; azaltmayı denemeye değer."),
        Phase.LimitFood("Alkol",
            "Sıvı dengesini ve uyku kalitesini bozabilir; bu günlerde yorgunluğu derinleştirebilir."),
        Phase.LimitFood("Kızartmalar",
            "Ağır ve yağlı yemekler sindirimi yavaşlatabilir, şişkinlik hissini artırabilir."),
        Phase.LimitFood("İşlenmiş şarküteri",
            "Tuz ve katkı oranı yüksektir; su tutulumunu artırabilir."),
        Phase.LimitFood("Şekerli gazlı içecekler",
            "Kan şekerini hızla oynatabilir; gaz ve şişkinliği artırabilir.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Çok acı yemekler",
            "Mide hassasiyeti olan bazı kişilerde şikâyeti artırabilir.",
            [TasteTag.Spicy]),
        Phase.LimitFood("Enerji içecekleri",
            "Kafein ve şekeri bir arada verir; çarpıntı ve huzursuzluğu artırabilir."),
        Phase.LimitFood("Hazır çorba ve bulyon",
            "Sodyumu yüksektir; sıcak içecek isteğini daha az tuzlu bir seçenekle karşılamak mümkün.",
            [TasteTag.LightSoup]),
        Phase.LimitFood("Beyaz unlu hamur işleri",
            "Hızlı yükselip düşen kan şekeri, yorgunluk hissini derinleştirebilir."),

        // --- İyi gelebilecek hareketler ---
        Phase.Exercise("Diyafram nefesi",
            "Yavaş nefes, gerginlik hissini azaltmaya yardımcı olabilir; oturarak da yapılabilir.",
            5,
            [TasteTag.Yoga]),
        Phase.Exercise("Boyun ve omuz gevşetme",
            "Kısa ve ekipmansız; gün içinde birkaç kez tekrarlanabilir.",
            5,
            [TasteTag.Stretching]),
        Phase.Exercise("Duvar desteğiyle esneme",
            "Denge derdi olmadan nazikçe uzamayı sağlar; ayakta yapılır.",
            6,
            [TasteTag.Stretching]),
        Phase.Exercise("Sandalyede oturarak esneme",
            "Ayakta durmak zor geldiğinde bile sürdürülebilir bir seçenek.",
            8,
            [TasteTag.Stretching]),
        Phase.Exercise("Kedi-inek hareketi",
            "Bel ve karın bölgesini nazikçe hareket ettirir; kramp hissini yumuşatabilir.",
            8,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Kelebek pozu",
            "Kalça içini nazikçe açar; nefesle birlikte yapmak rahatlatıcı olabilir.",
            8,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Ayakta hafif mobilite",
            "Ekipman gerektirmez; dolaşımı hareketlendirmek için kısa bir mola yeter.",
            10,
            [TasteTag.Stretching]),
        Phase.Exercise("Kısa ev içi yürüyüş",
            "Dışarı çıkmak istemediğin günler için; hareketsiz kalmamak bile fark yaratabilir.",
            10,
            [TasteTag.Walking]),
        Phase.Exercise("Çocuk pozu molası",
            "Bel bölgesini boşaltır; birkaç dakika kalmak bile gevşetici olabilir.",
            10,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Leğen eğimi",
            "Bel ve karın kaslarını zorlamadan çalıştırır; sırt üstü yapılır.",
            10,
            [TasteTag.Pilates],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Kalça açıcı esneme",
            "Bu bölgedeki gerginlik hissi kramplarla birlikte artabilir; nazik tutmak önemli.",
            12,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Sandalye pilatesi",
            "Yere inmeden yapılan kontrollü hareketler; düşük zorlukta başlar.",
            15,
            [TasteTag.Pilates]),
        Phase.Exercise("Sabah güneşinde kısa yürüyüş",
            "Gün ışığı ve hafif hareket, ruh hâline iyi gelebilir.",
            15,
            [TasteTag.Walking, TasteTag.Outdoor]),
        Phase.Exercise("Akşam sindirim yürüyüşü",
            "Yemek sonrası yavaş bir tur, şişkinlik hissini azaltmaya yardımcı olabilir.",
            15,
            [TasteTag.Walking, TasteTag.Outdoor]),
        Phase.Exercise("Yavaş tempolu ev dansı",
            "Sevdiğin bir şarkı kadar sürer; zorlamadan hareket etmenin keyifli yolu.",
            15,
            [TasteTag.Dance]),
        Phase.Exercise("Oturarak üst vücut hareketleri",
            "Bacaklara yük binmez; halsiz günlerde bile sürdürülebilir.",
            15,
            [TasteTag.Strength]),
        Phase.Exercise("Nazik yoga akışı",
            "Yavaş geçişlerle kısa bir akış; kas gerginliğini azaltmaya yardımcı olabilir.",
            20,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Nazik mat pilatesi",
            "Düşük tempoda, karın bölgesini zorlamayan bir seçki.",
            20,
            [TasteTag.Pilates],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Tam vücut esneme rutini",
            "Baştan aşağı kısa duruşlar; toparlanmaya odaklı bir seans.",
            20,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Düşük dirençli sabit bisiklet",
            "Tempoyu tamamen sen belirlersin; eklemlere darbe binmez.",
            20,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Hafif tempolu yürüyüş",
            "Konuşabildiğin bir tempo yeterli; dolaşımı destekler ve zorlamaz.",
            25,
            [TasteTag.Walking, TasteTag.Cardio]),
        Phase.Exercise("Ilık suda yüzme",
            "Su ağırlık hissini azaltır; ılık ortam kas gerginliğine iyi gelebilir.",
            25,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Restoratif yoga",
            "Destekli pozlarda uzun kalmaya dayanır; çaba değil gevşeme hedefler.",
            30,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Doğada yavaş yürüyüş",
            "Açık hava ve yavaş tempo; hem hareket hem zihinsel mola.",
            30,
            [TasteTag.Walking, TasteTag.Outdoor]),
        Phase.Exercise("Yin yoga",
            "Pozlarda dakikalarca kalınır; derin dokuları nazikçe açmayı hedefler.",
            35,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Uzun ve yavaş doğa yürüyüşü",
            "Enerjin varsa uzun ama sakin bir tur; molalarla bölmek iyi olabilir.",
            45,
            [TasteTag.Walking, TasteTag.Outdoor],
            [ContraTag.Knee]),

        Phase.Exercise("Ayakta yan esneme",
            "Gövde yanlarını açar; bel bölgesindeki gerginliği azaltabilir.",
            7,
            [TasteTag.Stretching]),
        Phase.Exercise("Sandalyede bel rotasyonu",
            "Oturarak yapılan kontrollü dönüş; masa başında bile mümkün.",
            8,
            [TasteTag.Pilates]),
        Phase.Exercise("Yatarak diz kucaklama",
            "Bel bölgesini boşaltır; kramp hissi olan günlerde rahatlatıcı olabilir.",
            8,
            [TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Sıcak duş sonrası esneme",
            "Kaslar ısınmışken esnemek daha rahat gelir ve zorlamayı azaltır.",
            10,
            [TasteTag.Stretching]),
        Phase.Exercise("Uyku öncesi gevşeme dizisi",
            "Yavaş hareketler ve nefes; uykuya geçişi kolaylaştırabilir.",
            12,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Duvara bacak dayama pozu",
            "Bacaklardaki ağırlık hissini azaltabilir; tamamen pasif bir poz.",
            12,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Kollar için hafif direnç hareketleri",
            "Bacaklara yük binmez; oturarak da yapılabilir.",
            12,
            [TasteTag.Strength]),
        Phase.Exercise("Yavaş akıcı hareket dizisi",
            "Tai chi benzeri sakin geçişler; denge ve nefese odaklanır.",
            15,
            [TasteTag.Yoga, TasteTag.Stretching]),
        Phase.Exercise("Düz zeminde kısa yürüyüş turu",
            "Eğim ve merdiven yok; en az zorlayan yürüyüş biçimi.",
            20,
            [TasteTag.Walking]),
        Phase.Exercise("Su içinde yavaş yürüyüş",
            "Su direnci kasları çalıştırır, ağırlık hissini ise azaltır.",
            20,
            [TasteTag.Walking, TasteTag.Cardio],
            [ContraTag.EquipmentGym]),

        // --- Şimdilik ertelenebilecek hareketler ---
        Phase.SkipExercise("Yoğun HIIT seansı",
            "Yüksek yoğunluk bu dönemde bazı kişilere ağır gelebilir; ertesi güne bırakılabilir.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Maksimum güç denemesi",
            "Kendini test etmek için iyi bir hafta olmayabilir; ağırlığı düşürmek yeterli.",
            [TasteTag.Strength]),
        Phase.SkipExercise("Uzun mesafe koşusu",
            "Uzun süreli yüksek tempo, yorgunluk hissini derinleştirebilir.",
            [TasteTag.Cardio]),
        Phase.SkipExercise("Ters duruşlar",
            "Baş ve omuz duruşları bu günlerde birçok kişiye rahatsız gelir.",
            [TasteTag.Yoga]),
        Phase.SkipExercise("Sıcak yoga",
            "Sıcak ortam sıvı kaybını artırabilir; baş dönmesi hissi yapabilir.",
            [TasteTag.Yoga]),
        Phase.SkipExercise("Zıplamalı pliometrik hareketler",
            "Darbe içeren hareketler kramp ve baskı hissini artırabilir.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Zorlu karın çalışması",
            "Karın bölgesine yüklenmek bu dönemde rahatsızlığı artırabilir.",
            [TasteTag.Strength]),
        Phase.SkipExercise("Yarışma temposunda grup dersi",
            "Kendi hızını koruyamadığın ortamlar bu hafta zorlayıcı olabilir.",
            [TasteTag.Cardio, TasteTag.Dance])
    ];
}
