using SereneCycle.Domain.Content;
using SereneCycle.Domain.Cycles;
using SereneCycle.Domain.Entities;

namespace SereneCycle.Infrastructure.Persistence;

/// <summary>
/// Ovulasyon kataloğu. Bu fazın izleği: enerjinin ve sosyal isteğin zirvesi,
/// buna karşılık artan eklem gevşekliği. Hareketlerde yoğun seçenekler var
/// ama sakatlık bayrağı olan kullanıcıda bunların çoğu sert filtreye takılır;
/// bu yüzden her yoğunluk seviyesinde kısıtsız alternatif de bulunuyor.
/// </summary>
internal static class OvulationSeedData
{
    private static readonly PhaseSeed Phase = new(CyclePhase.Ovulation);

    public static readonly IReadOnlyList<ContentItem> All =
    [
        // --- Öncelik verilebilecek yiyecekler ---
        Phase.Food("Renkli sebzeler",
            "Farklı renkler farklı antioksidanlar demek; tabağı çeşitlendirmek kolay bir hedef.",
            [TasteTag.Vegetables]),
        Phase.Food("Kuşkonmaz",
            "Folat içerir ve suyu boldur; hızlı pişen bir garnitür.",
            [TasteTag.Vegetables]),
        Phase.Food("Kırmızı biber",
            "C vitamini içeriği yüksek; çiğ tüketmek besin kaybını azaltır.",
            [TasteTag.Vegetables]),
        Phase.Food("Havuç",
            "Beta-karoten kaynağı; atıştırmalık olarak da iş görür.",
            [TasteTag.Vegetables]),
        Phase.Food("Domates",
            "Likopen içerir; zeytinyağıyla birlikte tüketmek emilimi destekler.",
            [TasteTag.Vegetables]),
        Phase.Food("Semizotu",
            "Suyu bol ve hafif; şişkinlik hissi olan günlerde iyi bir salata tabanı.",
            [TasteTag.LeafyGreens, TasteTag.Vegetables]),
        Phase.Food("Mevsim yeşillikleri salatası",
            "Lif ve su oranı yüksek; öğünlere hacim katar.",
            [TasteTag.LeafyGreens]),
        Phase.Food("Ispanaklı smoothie",
            "Yeşilliği meyveyle birleştirir; sabah aceleyken pratik bir seçenek.",
            [TasteTag.LeafyGreens, TasteTag.Fruit]),
        Phase.Food("Barbunya salatası",
            "Bitkisel protein ve lif; soğuk servis edilebildiği için hazırlığı esnek.",
            [TasteTag.Legumes, TasteTag.Vegetables]),
        Phase.Food("Mercimek köftesi",
            "Etsiz bir protein kaynağı; misafirlikte de iş gören bir seçenek.",
            [TasteTag.Legumes]),
        Phase.Food("Fava",
            "Bakla ezmesi; bitkisel protein ve folat içerir.",
            [TasteTag.Legumes]),
        Phase.Food("Kinoa salatası",
            "Tam tahılı sebzeyle birleştirir; öğle yemeğine taşınabilir.",
            [TasteTag.WholeGrains, TasteTag.Vegetables]),
        Phase.Food("Esmer pirinç",
            "Beyaz pirince göre lifi ve magnezyumu yüksek.",
            [TasteTag.WholeGrains]),
        Phase.Food("Yulaflı meyve kâsesi",
            "Lif ve doğal şekeri birleştirir; antrenman öncesi enerji verebilir.",
            [TasteTag.WholeGrains, TasteTag.Fruit],
            [ContraTag.Gluten]),
        Phase.Food("Izgara tavuk",
            "Yağı düşük protein; enerjinin yüksek olduğu günlerde toparlanmayı destekler.",
            [TasteTag.Poultry],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Hindi köftesi",
            "Kırmızı ete göre daha yağsız bir alternatif.",
            [TasteTag.Poultry],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Ton balıklı salata",
            "Protein ve sebzeyi hızlıca birleştirir; konserve suyu süzülerek kullanılabilir.",
            [TasteTag.Fish, TasteTag.Vegetables],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Alabalık",
            "Omega-3 içerir; fırında pişirmesi kolay bir balık.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan]),
        Phase.Food("Deniz ürünleri tabağı",
            "Çinko ve protein bakımından zengin; porsiyonu küçük tutmak yeterli olabilir.",
            [TasteTag.Fish],
            [ContraTag.Vegetarian, ContraTag.Vegan, ContraTag.Shellfish]),
        Phase.Food("Haşlanmış yumurta",
            "Taşınabilir bir protein; ara öğün sorununu çözer.",
            [TasteTag.Eggs],
            [ContraTag.Vegan, ContraTag.EggAllergy]),
        Phase.Food("Avokadolu yumurta",
            "Sağlıklı yağ ve proteini bir araya getirir; tokluğu uzatabilir.",
            [TasteTag.Eggs, TasteTag.Fruit],
            [ContraTag.Vegan, ContraTag.EggAllergy]),
        Phase.Food("Yoğurtlu semizotu",
            "Probiyotik ve yeşilliği birleştirir; sıcak günlerde ferahlatıcı.",
            [TasteTag.Dairy, TasteTag.LeafyGreens],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Ayran",
            "Sıvı ve elektrolit desteği; terlemenin arttığı günlerde iyi gelebilir.",
            [TasteTag.Dairy, TasteTag.Fermented],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Kefirli yeşil smoothie",
            "Probiyotik, yeşillik ve meyveyi tek bardakta toplar.",
            [TasteTag.Dairy, TasteTag.Fermented, TasteTag.Fruit],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Kabak çekirdeği",
            "Çinko kaynağı; bir tutamı salataya eklenebilir.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Ceviz ve badem karışımı",
            "Sağlıklı yağ ve magnezyum; porsiyonu bir avuçla sınırlamak yeterli.",
            [TasteTag.NutsAndSeeds],
            [ContraTag.TreeNuts]),
        Phase.Food("Chia tohumu",
            "Lif ve omega-3 içerir; suda beklettikten sonra tüketmek daha kolay.",
            [TasteTag.NutsAndSeeds]),
        Phase.Food("Karpuz",
            "Su oranı çok yüksek; sıvı alımını desteklemenin tatlı yolu.",
            [TasteTag.Fruit]),
        Phase.Food("Kavun",
            "Potasyum ve su içerir; hafif bir tatlı alternatifi.",
            [TasteTag.Fruit]),
        Phase.Food("Nar",
            "Antioksidan bakımından zengin; taneleri salataya da eklenebilir.",
            [TasteTag.Fruit]),
        Phase.Food("Bitter çikolatalı meyve",
            "Tatlı isteğini lif ve magnezyumla birlikte karşılar.",
            [TasteTag.Sweet, TasteTag.Fruit]),
        Phase.Food("Hurmalı enerji topu",
            "Kuruyemiş ve hurmadan yapılır; antrenman öncesi küçük bir porsiyon yeterli.",
            [TasteTag.Sweet, TasteTag.NutsAndSeeds],
            [ContraTag.TreeNuts]),
        Phase.Food("Zencefilli limonata",
            "Ferahlatıcı ve şekersiz hazırlanabilir; sıvı alımını artırır.",
            [TasteTag.Spicy]),
        Phase.Food("Baharatlı nohut kavurma",
            "Çıtır bir atıştırmalık; cips yerine lifli bir seçenek.",
            [TasteTag.Spicy, TasteTag.Legumes]),
        Phase.Food("Soğuk yoğurt çorbası",
            "Sıcak günlerde hafif bir öğün; probiyotik de içerir.",
            [TasteTag.LightSoup, TasteTag.Dairy],
            [ContraTag.Vegan, ContraTag.Lactose]),
        Phase.Food("Sebze suyuna çorba",
            "Hafif ve sıvı ağırlıklı; akşam öğününü ağırlaştırmadan doyurur.",
            [TasteTag.LightSoup, TasteTag.Vegetables]),

        // --- Sınırlı tutulabilecek yiyecekler ---
        Phase.LimitFood("Alkol",
            "Uyku kalitesini ve ruh hâli dengesini bozabilir."),
        Phase.LimitFood("Aşırı tuz",
            "Bazı kişilerde bu günlerde de şişkinlik hissi olur; tuzu azaltmak yardımcı olabilir."),
        Phase.LimitFood("Şekerli içecekler",
            "Hızlı yükselen kan şekeri, ardından gelen düşüşle enerjiyi geri çeker.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Aşırı kafein",
            "Enerjisi zaten yüksek bir dönemde huzursuzluk ve çarpıntı hissini artırabilir."),
        Phase.LimitFood("Çok yağlı kızartmalar",
            "Sindirimi yavaşlatır; antrenman öncesi rahatsızlık verebilir."),
        Phase.LimitFood("İşlenmiş etler",
            "Tuz ve katkı oranı yüksektir; sık tüketimi önerilmez."),
        Phase.LimitFood("Çok büyük porsiyonlar",
            "İştahın arttığı günlerde porsiyonu bölmek daha rahat hissettirebilir."),
        Phase.LimitFood("Yalnızca kafeinli içeceklerle sıvı almak",
            "Su yerine kahve içmek sıvı dengesini bozabilir; araya su eklemek iyi olur."),
        Phase.LimitFood("Şekerli sporcu içecekleri",
            "Normal bir antrenman için gerekmez; suyla birlikte tuzlu bir atıştırmalık yeterli olabilir.",
            [TasteTag.Sweet]),
        Phase.LimitFood("Gece geç saatte ağır yemek",
            "Uykuya geçişi zorlaştırabilir; akşam öğününü öne almak yardımcı olur."),

        // --- İyi gelebilecek hareketler ---
        Phase.Exercise("Dinamik ısınma ve mobilite",
            "Eklem gevşekliğinin arttığı bu dönemde ısınmayı atlamamak daha da önemli.",
            8,
            [TasteTag.Stretching]),
        Phase.Exercise("Serbest dans molası",
            "Enerjini boşaltmanın en kısa yolu; iki şarkı yeterli.",
            10,
            [TasteTag.Dance]),
        Phase.Exercise("Kısa esneme ve soğuma",
            "Antrenman sonrası nabzı düşürür; ekipman gerekmez.",
            10,
            [TasteTag.Stretching]),
        Phase.Exercise("Kısa yürüyüş molası",
            "Gün içine sıkıştırılabilir; hareketsiz kalmamak da bir kazanç.",
            10,
            [TasteTag.Walking]),
        Phase.Exercise("Yerinde yüksek diz",
            "Kısa sürede nabzı zirveye çıkarır; darbe içerir.",
            10,
            [TasteTag.Cardio, TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Ayakta denge yogası",
            "Denge duruşları güç ve dikkat ister; yere inmeyi gerektirmez.",
            12,
            [TasteTag.Yoga]),
        Phase.Exercise("Duvar pilatesi",
            "Mat gerektirmez; merkez bölgeyi kontrollü çalıştırır.",
            15,
            [TasteTag.Pilates]),
        Phase.Exercise("Şınav ve plank çalışması",
            "Üst vücut ve merkez bölgeyi hedefler; dizden destekli varyasyonu da var.",
            15,
            [TasteTag.Strength],
            [ContraTag.Shoulder, ContraTag.Pregnancy]),
        Phase.Exercise("Tabata",
            "Dört tur yüksek yoğunluk; birçok kişi bu günlerde kendini en güçlü hisseder.",
            16,
            [TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("HIIT devresi",
            "Kısa ve yoğun aralıklar; enerjinin zirvede olduğu günlere denk gelir.",
            20,
            [TasteTag.Hiit, TasteTag.Cardio],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Vücut ağırlığıyla kuvvet devresi",
            "Ekipmansız ama zorlayıcı; tekrar sayısını kendine göre ayarla.",
            20,
            [TasteTag.Strength],
            [ContraTag.Knee]),
        Phase.Exercise("Tempolu yürüyüş",
            "Yoğun bir seans istemediğin günler için sağlam bir varsayılan.",
            25,
            [TasteTag.Walking, TasteTag.Cardio]),
        Phase.Exercise("Sprint tekrarları",
            "Kısa hızlı koşular ve yürüyerek toparlanma; darbe yüksek.",
            25,
            [TasteTag.Hiit, TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Tempolu koşu",
            "Enerjinin yüksek olduğu bu günlerde mesafeyi uzatmak kolay gelebilir.",
            30,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Zumba",
            "Dansı kardiyoyla birleştirir; sosyal enerjinin yüksek olduğu bir döneme uygun.",
            30,
            [TasteTag.Dance, TasteTag.Cardio],
            [ContraTag.Knee]),
        Phase.Exercise("Power yoga",
            "Kuvvet odaklı bir yoga türü; eklemleri son sınıra zorlamamak önemli.",
            30,
            [TasteTag.Yoga, TasteTag.Strength],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Mat pilatesi",
            "Orta tempoda kontrollü hareketler; merkez bölgeyi çalıştırır.",
            30,
            [TasteTag.Pilates],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Dambıllı kuvvet devresi",
            "Yükü kademeli artırmak için uygun bir hafta olabilir.",
            35,
            [TasteTag.Strength],
            [ContraTag.EquipmentDumbbell]),
        Phase.Exercise("Tempolu yüzme",
            "Tüm vücudu çalıştırır; eklem gevşekliğine rağmen darbe içermez.",
            35,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Vinyasa yoga",
            "Akıcı geçişler; nefesle senkron çalışmak dikkati toplar.",
            40,
            [TasteTag.Yoga],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Dans dersi",
            "Sosyal enerjinin yüksek olduğu bir dönem için eğlenceli bir seçenek.",
            45,
            [TasteTag.Dance, TasteTag.Cardio]),
        Phase.Exercise("Kutu boks dersi",
            "Yüksek yoğunluk ve koordinasyon; omuzlara belirgin yük biner.",
            45,
            [TasteTag.Hiit, TasteTag.Cardio],
            [ContraTag.EquipmentGym, ContraTag.Shoulder]),
        Phase.Exercise("Spinning dersi",
            "Grup enerjisiyle yoğun kardiyo; direnci kendin ayarlayabilirsin.",
            45,
            [TasteTag.Cardio],
            [ContraTag.EquipmentGym, ContraTag.Knee]),
        Phase.Exercise("Salonda alt vücut günü",
            "Ekipman çeşitliliği kademelendirmeyi kolaylaştırır; forma dikkat.",
            45,
            [TasteTag.Strength],
            [ContraTag.EquipmentGym, ContraTag.Knee]),
        Phase.Exercise("Grup sporları",
            "Voleybol ya da basketbol gibi; sosyal enerjinin yüksek olduğu bir dönem.",
            60,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Uzun bisiklet turu",
            "Açık havada uzun bir tur; enerjini değerlendirmenin keyifli yolu.",
            60,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Doğa yürüyüşü",
            "Eğimli parkurlar bu dönemde daha kolay gelebilir; ayakkabı seçimi önemli.",
            60,
            [TasteTag.Walking, TasteTag.Outdoor],
            [ContraTag.Knee]),

        Phase.Exercise("Squat sıçraması",
            "Patlayıcı bir alt vücut hareketi; enerjinin zirvede olduğu günlere uygun.",
            12,
            [TasteTag.Hiit],
            [ContraTag.Knee, ContraTag.Pregnancy]),
        Phase.Exercise("Burpee serisi",
            "Tüm vücudu çalıştıran yoğun bir hareket; tekrar sayısını düşük tutarak başla.",
            12,
            [TasteTag.Hiit, TasteTag.Strength],
            [ContraTag.Knee, ContraTag.Back, ContraTag.Pregnancy]),
        Phase.Exercise("Hızlı yürüyüş intervalleri",
            "İki dakika hızlı, iki dakika normal; ekipman ya da salon gerekmez.",
            20,
            [TasteTag.Walking, TasteTag.Cardio]),
        Phase.Exercise("Yoga ile aktif toparlanma",
            "Yoğun bir günün ertesinde kasları açar, tempoyu düşürür.",
            20,
            [TasteTag.Yoga, TasteTag.Stretching],
            [ContraTag.EquipmentMat]),
        Phase.Exercise("Kürek makinesi",
            "Kardiyo ve kuvveti birleştirir; sırt formunu korumak önemli.",
            25,
            [TasteTag.Cardio, TasteTag.Strength],
            [ContraTag.EquipmentGym, ContraTag.Back]),
        Phase.Exercise("Koşu bandında interval",
            "Hız ve eğimi kontrol edebildiğin için yoğunluğu kademelendirmek kolay.",
            25,
            [TasteTag.Cardio, TasteTag.Hiit],
            [ContraTag.EquipmentGym, ContraTag.Knee]),
        Phase.Exercise("Dambıllı omuz ve sırt",
            "Üst vücuda odaklanır; ağırlığı formu bozmayacak seviyede tut.",
            25,
            [TasteTag.Strength],
            [ContraTag.EquipmentDumbbell, ContraTag.Shoulder]),
        Phase.Exercise("Tempolu bisiklet intervali",
            "Açık havada hızlı ve yavaş turları dönüşümlü sürmek.",
            30,
            [TasteTag.Cardio, TasteTag.Hiit, TasteTag.Outdoor],
            [ContraTag.Knee]),
        Phase.Exercise("Reformer pilates",
            "Aletli pilates; direnci ayarlanabildiği için zorluk kademelenir.",
            45,
            [TasteTag.Pilates],
            [ContraTag.EquipmentGym]),
        Phase.Exercise("Tenis ya da badminton",
            "Sosyal ve rekabetçi; ani yön değişimleri içerdiği için ısınma önemli.",
            45,
            [TasteTag.Cardio, TasteTag.Outdoor],
            [ContraTag.Knee, ContraTag.Shoulder]),

        // --- Şimdilik ertelenebilecek hareketler ---
        Phase.SkipExercise("Aşırı zorlanma",
            "Kendini iyi hissetmek, sınırları zorlamak anlamına gelmiyor."),
        Phase.SkipExercise("Eklemi son sınıra zorlayan esnemeler",
            "Bu dönemde eklem gevşekliği artabilir; aşırı esneme sakatlanma riskini yükseltir.",
            [TasteTag.Stretching]),
        Phase.SkipExercise("Isınmasız patlayıcı hareket",
            "Hazırlıksız sıçrama ve sprint, bu fazda daha riskli olabilir.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Aynı gün iki yoğun seans",
            "Enerji yüksekken program aşmak, sonraki günlerin toparlanmasını borçlandırır.",
            [TasteTag.Hiit]),
        Phase.SkipExercise("Ani yön değiştiren sporlar",
            "Sakatlık öyküsü varsa bu hafta daha temkinli olmak iyi olabilir.",
            [TasteTag.Cardio]),
        Phase.SkipExercise("Ağrıya rağmen sürdürmek",
            "Yorgunluk ile ağrı farklıdır; ağrı bir durma sinyali olarak okunabilir."),
        Phase.SkipExercise("Uykusuz günde yoğun antrenman",
            "Uyku borcu varken yoğunluğu artırmak toparlanmayı zorlaştırır."),
        Phase.SkipExercise("Soğuma yapmadan bitirmek",
            "Yoğun seansın ardından beş dakikalık soğuma, kas ağrısını azaltmaya yardımcı olabilir.",
            [TasteTag.Stretching])
    ];
}
