// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SereneCycle.Infrastructure.Persistence;

#nullable disable

namespace SereneCycle.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814141836_PeriodLogAndProfileEditing")]
    partial class PeriodLogAndProfileEditing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Phase", "Type");

                    b.ToTable("content_items", (string)null);
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("PeriodDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_cycles_user_start_unique");

                    b.ToTable("cycles", (string)null);
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Flow")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBleeding")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSpotting")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_logs_user_date_unique");

                    b.ToTable("daily_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_logs_flow_range", "\"Flow\" IS NULL OR \"Flow\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.FoodPhaseScore", b =>
                {
                    b.Property<string>("FoodClass")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Phase")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("FoodClass", "Phase");

                    b.ToTable("food_phase_scores", (string)null);
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.LogSymptom", b =>
                {
                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.HasKey("LogId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("log_symptoms", (string)null);
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("symptoms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Physical",
                            Name = "Karın krampları"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Physical",
                            Name = "Baş ağrısı"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Physical",
                            Name = "Şişkinlik"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Physical",
                            Name = "Göğüs ağrısı"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Physical",
                            Name = "Yorgunluk"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Physical",
                            Name = "Akne"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Physical",
                            Name = "Bel ağrısı"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Physical",
                            Name = "İştah değişikliği"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Physical",
                            Name = "Ateş basması"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Physical",
                            Name = "Bulantı"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Physical",
                            Name = "Cilt kuruluğu"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Physical",
                            Name = "Gece terlemeleri"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Physical",
                            Name = "Hafıza kaybı"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Physical",
                            Name = "İdrar kaçırma"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Physical",
                            Name = "İshal"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Physical",
                            Name = "Kabızlık"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Physical",
                            Name = "Pelvis ağrısı"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Physical",
                            Name = "Saç dökülmesi"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Physical",
                            Name = "Uyku değişiklikleri"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Physical",
                            Name = "Üşüme"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Physical",
                            Name = "Vajina kuruluğu"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Mood",
                            Name = "Enerjik"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Mood",
                            Name = "Sakin"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Mood",
                            Name = "Mutlu"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Mood",
                            Name = "Hüzünlü"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Mood",
                            Name = "Kaygılı"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Mood",
                            Name = "Sinirli"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Mood",
                            Name = "Odaklı"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Mood",
                            Name = "Hassas"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Mood",
                            Name = "Duygudurum değişiklikleri"
                        });
                });

            modelBuilder.Entity("SereneCycle.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("AvatarData")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("AvatarUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AvgCycleLength")
                        .HasColumnType("integer");

                    b.Property<int>("AvgPeriodLength")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EmailChangeAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EmailChangeCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailChangeCodeHash")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("VerificationAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("VerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationCodeHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SereneCycle.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SereneCycle.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SereneCycle.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SereneCycle.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SereneCycle.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.LogSymptom", b =>
                {
                    b.HasOne("SereneCycle.Domain.Entities.DailyLog", "Log")
                        .WithMany("LogSymptoms")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SereneCycle.Domain.Entities.Symptom", "Symptom")
                        .WithMany("LogSymptoms")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("SereneCycle.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("SereneCycle.Infrastructure.Identity.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.DailyLog", b =>
                {
                    b.Navigation("LogSymptoms");
                });

            modelBuilder.Entity("SereneCycle.Domain.Entities.Symptom", b =>
                {
                    b.Navigation("LogSymptoms");
                });

            modelBuilder.Entity("SereneCycle.Infrastructure.Identity.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
